### ISSUE TITLE
Relogin ~3times per day

### ISSUE THREAD

**Issue by Bysmyyr** [Dax89/harbour-sailorgram#1]
Thanks! This looks very good. One bug that's happening in me. I have to login quite often. The program ask for new key automatically but then I have to submit it myself. This happens 2-3 times per day or something.

**Comment by Dax89** [comment]
Hi!

The automatic login works in this way:
SailorGram stores your phone number and the server's authorization key in settings and, next time you launch the application, it will send automatically these informations to Telegram servers skipping the authorization part.

Can you reset the application by deleting the folder "harbour-sailorgram" located in /home/nemo/.local ?

The application will ask you the phone number again, if the issue persists, try to launch the application from Terminal and post here the output so I can fix it!

**Comment by Dax89** [comment]
Can I close this issue? Or is stll present?

**Comment by Bysmyyr** [comment]
Yep, it stopped rigth after I asked it :) now it works fine

**Comment by Dax89** [comment]
Ok!
