### ISSUE TITLE
Telegram's stickers are not displayed

### ISSUE THREAD

**Issue by mrzapp** [Dax89/harbour-sailorgram#18]
SailfishOS uses Qt 5.2 and Telegram's stickers are not displayed becaus WebP format is not supported (this can be fixed implementing a Qml component ourselves until Sailfish updates to Qt 5.5)

**Comment by rollator** [comment]
i believe this was implemented in version 0.79-1, wasn't it?

**Comment by Dax89** [comment]
Mmmmh, yes they are, I've missed to close this issue :)
Thanks for reporting
