### ISSUE TITLE
Integration with Messages app

### ISSUE THREAD

**Issue by d9h02f** [Dax89/harbour-sailorgram#24]
This isn't really a feature request for this app but I didn't know where else to put it.

It would be great if Telegram could be integrated in the Messages app, through a Telepathy connection manager. That way, you would be able to add an account from the system settings, and it would even be possible to use it with desktop clients like Empathy that use Telepathy as backend.

The integration of all different services in one place is one of the greatest strengths of Sailfish OS (and other modern OS's), so even though it's great to have different great apps like this one, I think it's even better to have just one app for all messaging services.

If you're interested, the Telepathy website seems to be mostly unavailable right now, but the developer's manual is available here: https://web.archive.org/web/20140805163335/http://telepathy.freedesktop.org/doc/book/index.html
Maybe this can also be of help: http://www.aosabook.org/en/telepathy.html

**Comment by a-andreyev** [comment]
not sure how it connected with the [Aseman componets](https://github.com/Aseman-Land),
but there is a [telepathy-morse for telegram](https://github.com/TelepathyQt)

**Comment by d9h02f** [comment]
Thanks for that link, they also seem to have a connection manager for Google Hangouts (but judging by the lack of activity on it, it probably doesn't work yet).

**Comment by Dax89** [comment]
They are two different projects, it means a complete rewrite of the client.

However, in the future, nothing prevents to develop a Telepathy plugin using Aseman components
