### ISSUE TITLE
Text disappears when typing a mesage with more then 2 lines

### ISSUE THREAD

**Issue by PawelSpoon** [Dax89/harbour-sailorgram#25]
Great, when everything else works and such small usability issues become visible ! Realy great Job.
So, Type a message with 3 lines. The textbox or whatever controll that is still show first line comple, second partly cut of and third invisible.
The line and the cursor are hidden behind keyboard

**Comment by TAHassing** [comment]
I'd like to confirm that the text box in the chat screen shows the same behaviour on my phone since I upgraded to v72-1.

**Comment by PawelSpoon** [comment]
fixed in 0.72 preview from 22.12.2015
