### ISSUE TITLE
Sorting of images (files) in folders

### ISSUE THREAD

**Issue by PawelSpoon** [Dax89/harbour-sailorgram#27]
when i browse for pictures ie in camera folder, i have always to scroll down to the latest
i have now 1000 pics
it would be great to reverse the sorting order
gallery is also showing the latest first.

**Comment by Dax89** [comment]
Fixed in https://github.com/Dax89/harbour-sailorgram/commit/4d9d671e06aa248731e81b80994087913d3651b3
