### ISSUE TITLE
Crash during browsing for an pic

### ISSUE THREAD

**Issue by PawelSpoon** [Dax89/harbour-sailorgram#3]
Hi, first thanks for the app ! Really the best Telegram client for Sailfish
What i do experience is an crash during browsing for attachments.
it is a 50% chance.
i click on attach then browse into pictures and while the thumbs are generated the app crashes

**Comment by Dax89** [comment]
The issue is triggered by SailfishOS' OOM Killer.
It usually happens when there are lots of image in the same folder, I have disabled thumbnails
