### ISSUE TITLE
message sent from SailorGram always quotes chat's first message

### ISSUE THREAD

**Issue by sledges** [Dax89/harbour-sailorgram#31]
If another contact starts conversation, let's say with "Hello and welcome!", all my subsequent messages show up on their (Android) app quoting their very first message, e.g.:

>\> Hello and welcome!
Are you saying that you always see "Hello and welcome!" above every text of mine?

When they delete the whole conversation, problem fixes itself, but today it started to appear again :( (yesterday I installed Linux Telegram client, so I can confirm seeing my own messages appearing as replies there, I can also provide screenshots from how it looks on Android app)

Many thanks for ongoing effort!

**Comment by Dax89** [comment]
Probably the 'reply' flag always set on true, that's why you see the quoted message with the official client (in Sailorgram 0.7x quoted message aren't implemented).

Btw, it is already fixed in 0.8x branch, because the new library is different :) https://github.com/Dax89/harbour-sailorgram/tree/0.8

**Comment by sledges** [comment]
Thanks for reply; awesome news! Can't wait to test 0.8 :)

It is weird behaviour, that it quotes always the opener message of a conversation, and not the last one. I thought if reply flag was on, it would quote each last message. But irrelevant in 0.8 as you said ;)

**Comment by Dax89** [comment]
Fixed and tested with the new MessageBar implementation! :)
https://github.com/Dax89/harbour-sailorgram/blob/master/harbour-sailorgram/qml/items/dialog/DialogTextInput.qml

**Comment by sledges** [comment]
Just checked Warehouse for updates, nothing yet :{ :D

**Comment by Dax89** [comment]
I'm doing some code adjustements and testing it on my jolla phone.

I will release it tomorrow, if everything goes well! :)

**Comment by Dax89** [comment]
I couldn't resist: this is the internal beta testing package: https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.72-10.armv7hl.rpm

Some features are not implemented or incomplete because I'm working on it now
Do not use secret chats, I need to test it!

**Comment by Dax89** [comment]
Beta Testing is taking some time, this is the third preview: https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.72-12.armv7hl.rpm

**Comment by sledges** [comment]
Verified this issue fixed correctly \o/ many thanks!!! :+1:
