### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by adithyakhamithkar** [Dax89/harbour-sailorgram#33]
Hi,

Every time I open the application it prompts me to enter the code from sms. Can this be avoided? 

Thanks,

**Comment by lewadedun** [comment]
everything ok for me

**Comment by Dax89** [comment]
Try to reset SailorGram by deleting the folder named "harbour-sailorgram" located in /home/nemo/.local/share and repeat the sign-in procedure!

**Comment by adithyakhamithkar** [comment]
@Dax89 I did try that still have the same problem.

**Comment by Dax89** [comment]
Can I close this one?

**Comment by adithyakhamithkar** [comment]
Yes after upgrading to the new version i don't have the problem now.

Thanks
