### ISSUE TITLE
0.72-12 does not upload photos

### ISSUE THREAD

**Issue by sledges** [Dax89/harbour-sailorgram#36]
The new testing version [1] fixed issue https://github.com/Dax89/harbour-sailorgram/issues/31, but started failing to upload photos.

The progress does not appear in the log, reverted to 0.72-2 for now.

[1] https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.72-12.armv7hl.rpm

**Comment by Dax89** [comment]
I have fixed that today and the fix will be available in the next beta!

**Comment by Dax89** [comment]
Try this version: https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.72-13.armv7hl.rpm

**Comment by Dax89** [comment]
Updated package, revision 14:

https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.72-14.armv7hl.rpm

**Comment by sledges** [comment]
It worked! \o/ Thanks :+1: 
Another big thanks for image previews button before uploading, and sorting newest first!

**Comment by Dax89** [comment]
There should be a (last) beta and if testing goes well it will be available in open repos as version 0.73 :)
