### ISSUE TITLE
Sailorgram crashing after update to 0.73-1

### ISSUE THREAD

**Issue by adithyakhamithkar** [Dax89/harbour-sailorgram#37]
Hey thanks for the update with a lot of new features.
sailorgram crashing is taking a very long time to load and it crashes while authenticating.

Can you please let me know what to do to fix this?

Thanks,

**Comment by PawelSpoon** [comment]
start from cli, collect the log and upload the log in github


On Thu, 31 Dec 2015 01:22:34 +0100, Adithya Khamithkar  
<notifications@github.com> wrote:

>
> Hey thanks for the update with a lot of new features
> sailorgram crashing is taking a very long time to load and it crashes  
> while authenticating
>
> Can you please let me know what to do to fix this?
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Using Opera's mail client: http://www.opera.com/mail/

**Comment by Dax89** [comment]
Try this version!
https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.73-2.armv7hl.rpm

**Comment by adithyakhamithkar** [comment]
I am still have the same problem after installing 0.73-2
Can you please tell me how to start it from CLI and collect the logs I'll upload it here.

**Comment by Dax89** [comment]
Have you tried to delete the "harbour-sailorgram" folder in /home/nemo/.local/share?
Maybe it needs to get the new telegram data centers (they are not updated automatically) from scratch

This is the procedure in order to get logs from an application: https://together.jolla.com/question/103763/how-to-start-an-app-from-terminal-and-collect-log/

For example:
```
harbour-sailorgram 2>&1 > log.txt
```

**Comment by adithyakhamithkar** [comment]
I am getting this error.
```
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[D] DeclarativeCoverActionList::appendActions:143 - static void DeclarativeCoverActionList::appendActions(QQmlListProperty<DeclarativeCoverAction>*, DeclarativeCoverAction*)  QUrl( "image://theme/icon-cover-message" )
[D] Utils::rsaLoadPublicKey:273 - public key "/usr/share/harbour-sailorgram/server.pub" loaded successfully
[D] Settings::loadSettings:161 - loaded Telegram public key from file: "/usr/share/harbour-sailorgram/server.pub"
[D] Settings::loadSettings:164 - loading configuration from path: "/home/nemo/.local/share/harbour-sailorgram/harbour-sailorgram/telegram/+919886053953"
[D] Settings::loadSettings:191 - loading settings file "/home/nemo/.local/share/harbour-sailorgram/harbour-sailorgram/telegram/+919886053953/config"
[D] Settings::loadSettings:202 - testMode: false
[D] Settings::loadSettings:203 - managedDownloads: false
[D] Settings::loadSettings:204 - lang: "en"
[D] Settings::loadSettings:205 - authFile: "/home/nemo/.local/share/harbour-sailorgram/harbour-sailorgram/telegram/+919886053953/auth"
[D] Settings::loadSettings:206 - secretChatFile: "/home/nemo/.local/share/harbour-sailorgram/harbour-sailorgram/telegram/+919886053953/secret"
[D] Settings::loadSettings:207 - stateFile: "/home/nemo/.local/share/harbour-sailorgram/harbour-sailorgram/telegram/+919886053953/state"
[D] Settings::readAuthFile:261 - workingDcNum: 5
[D] Settings::readAuthFile:262 - ourId: 0
[D] Settings::readAuthFile:284 - DC | id: 0 , state: 0 , host: "" , port: 0 , expires: 0 , authKeyId: 0 , serverSalt: 0
[D] Settings::readAuthFile:284 - DC | id: 1 , state: 0 , host: "149.154.175.50" , port: 443 , expires: 0 , authKeyId: -4201216362570216186 , serverSalt: 981450843339695549
[D] Settings::readAuthFile:284 - DC | id: 2 , state: 0 , host: "149.154.167.51" , port: 443 , expires: 0 , authKeyId: -2741892845272039563 , serverSalt: 2762904671041902962
[D] Settings::readAuthFile:284 - DC | id: 3 , state: 0 , host: "149.154.175.100" , port: 443 , expires: 0 , authKeyId: 1369578725832443256 , serverSalt: -4277922893010192858
[D] Settings::readAuthFile:284 - DC | id: 4 , state: 0 , host: "149.154.167.91" , port: 443 , expires: 0 , authKeyId: 3913934596130902484 , serverSalt: 3432619608897681363
[D] Settings::readSecretFile:323 - secret chats dh version: 0
[D] Settings::readSecretFile:324 - secret chats g: 0
[D] Settings::readSecretFile:325 - secret chats p: ""
Segmentation fault
```

**Comment by adithyakhamithkar** [comment]
I will try deleting the harbour-sailorgram and let you know.

**Comment by adithyakhamithkar** [comment]
OK It's working after deleting the harbour-sailorgram :+1: 
I had one question does the app run as a daemon?

**Comment by Dax89** [comment]
Do you use secret chats?
I advice to reduce its use, because they needs a lots of fixes! :)

No, currently there is no daemon, but I will implement it!

**Comment by adithyakhamithkar** [comment]
Cool thanks I don't use it that much.

I'll look forward for the daemon

**Comment by Dax89** [comment]
Ok! :+1:
