### ISSUE TITLE
links are not shown in Sailorgram

### ISSUE THREAD

**Issue by PawelSpoon** [Dax89/harbour-sailorgram#41]
i did sent a message that contists only of an weblink. in sailorgram the message looks like beeing empty.
if i open telegram android app, i can see the link

version 0.73-13

**Comment by mentaljam** [comment]
I can confirm this issue. Messages with only one web-link are shown empty but after sending more messages in the conversation and restarting the SailorGram everything looks okay.

**Comment by Dax89** [comment]
It's fixed in the upcoming beta :)

**Comment by Dax89** [comment]
Uploaded: https://dl.dropboxusercontent.com/u/40206233/Progetti/harbour-sailorgram-0.73-14.armv7hl.rpm :)
