### ISSUE TITLE
No check marks in conversations

### ISSUE THREAD

**Issue by mentaljam** [Dax89/harbour-sailorgram#44]
I didn't notice when check marks have disappeared, but for now I have only a timestamp under my messages. I use the latest version from the master (0.73-17).

![screenshot_2016-1-24_23_46_29 769](https://cloud.githubusercontent.com/assets/6236802/12538847/a0cfd056-c2f5-11e5-9089-8e4b8887966b.png)

**Comment by Dax89** [comment]
Mmmh, I can't reproduce with the upstram version, I'll keep this issue open so you can test it with the next beta :)

**Comment by mentaljam** [comment]
So, it looks like the problem depends on the locale. I changed my phone language to English (UK) and check marks had returned. After I switched back to Russian check marks had disappeared again.

**Comment by Dax89** [comment]
I'm using the "tick" character (so I can change it according to the ambience color).

**Comment by mentaljam** [comment]
If I change the '✓' character in the 'MessageStatus.qml' for something different (I tried '!') then it's showed. So may be it's a font issue? Then why I have seen check marks in past?

**Comment by Dax89** [comment]
In 0.73-16 that character was visible?
It can be a font issue, or I have introduced a regression between 0.73-16 -> 17

**Comment by mentaljam** [comment]
I tried to install SailorGram from OpenRepos (0.73-5) and had the same issue (when changed versions I removed all SailorGram files I found in file system).
Also I have recently updated Sailfish to 2.0.1.7 - maybe it has something to do... The trouble is I can't tell when exactly check marks disappeared...

**Comment by Dax89** [comment]
There is a checkmark character that you can see?
I can change it :)

**Comment by mentaljam** [comment]
Can you switch to Russian locale and check if you see this character? Maybe it's only my device problem.
By the way I created a text file with this checkmark and opened it in FileCase text viewer and it's visible.

**Comment by Dax89** [comment]
Ok, I have the same issue with the Russian locale!

**Comment by Dax89** [comment]
It's strange, if I add a character before the checkmarks or I change the Label style to "PlainText" they are displayed correctly

**Comment by mentaljam** [comment]
Also if the timestamp part is removed (TelegramHelper.printableDate(message.date)) then check marks are displayed.

**Comment by mentaljam** [comment]
I created a new blank application with just two labels with Latin and Cyrillic characters and check marks.

On my jolla phone check marks are not shown after Cyrillic neither on Russian locale nor English:
![phone](https://cloud.githubusercontent.com/assets/6236802/12859296/4be48a44-cc66-11e5-926d-2f42b3a21cc0.png)

On the emulator check marks are shown normally:
![emulator](https://cloud.githubusercontent.com/assets/6236802/12859312/5d8cae84-cc66-11e5-9f81-505cd712f84f.png)

**Comment by Dax89** [comment]
It can be related to Sailfish 2.0.1.7?
Did you have tried to change the font?

**Comment by mentaljam** [comment]
> It can be related to Sailfish 2.0.1.7?

I don't know. The emulator has Sailfish 2.0.0.10

>  Did you have tried to change the font?

No, I did not. I will try when I have time.

**Comment by mentaljam** [comment]
Ok, I've installed the "[Sailfish Extra Fonts (mostly for Cyrillic and Greek)](https://openrepos.net/content/gnikandrov/sailfish-extra-fonts-mostly-cyrillic-and-greek)" package from OpenRepos and checkmarks were back... So it is definitely a problem of the Sailfish OS font.

**Comment by Dax89** [comment]
Is this issue sill present in Sailfish 2.0.2.x ? :)

**Comment by mentaljam** [comment]
I tried to remove extra fonts and reboot and check-marks are there. So it seems that the issue can be closed. (Sailfish OS 2.0.2.48)

**Comment by Dax89** [comment]
Ok! Thanks :)
