### ISSUE TITLE
sailorgram&CPU

### ISSUE THREAD

**Issue by lewadedun** [Dax89/harbour-sailorgram#45]
sailorgram uses 50-70% of CPU, if you switch from cellular network to Wi Fi. Or from Wi Fi to cellular network. sailorgram cannot connect to the network, as I understand it.
0.73-beta 14

**Comment by Dax89** [comment]
I was figuring out how to reproduce this issue, so I need to switch from mobile to wifi (or viceversa), thanks :)

**Comment by PawelSpoon** [comment]
have a similiar issue here now on 2.0.10
when i switch from mobile to wifi, sailorgram can't connect and the menu is not reactive. it s almost impossible to reach exit menu item.
i have to kill from the 'outside'

thanks for all the other new features!

**Comment by Dax89** [comment]
This should be fixed in 5e6145b.
Is this issue still present in the latest beta?

**Comment by Dax89** [comment]
Seems to be fixed, when I have changed from QNetworkConfigurationManager to Connman
