### ISSUE TITLE
Can't see shared contacts

### ISSUE THREAD

**Issue by Tichy** [Dax89/harbour-sailorgram#49]
Shared contacts' posts are shown blank.
See screenshot to compare the same posts on web telegram, cutegram and sailorgram.
![screenshot-16-02-02-13-42-41](https://cloud.githubusercontent.com/assets/2348771/12750194/dd5363be-c9b5-11e5-9bc5-5bf9bf6c5b17.png)

**Comment by Dax89** [comment]
Fixed in #73
