### ISSUE TITLE
Cancel file transfer

### ISSUE THREAD

**Issue by Dax89** [Dax89/harbour-sailorgram#5]
Transfers are not cancelled when calling cancelDownload() or cancelSendGet() needs investigation

**Comment by JustDevZero** [comment]
I don't know if it's already "solved" in the new version, but I can confirm It's not happening always. Sometimes the file transfer gets cancelled, other times not, it's indeed pretty weird.

**Comment by Dax89** [comment]
Yes, a fix is planned in 0.8
If everything goes well, I should implement file transfer (cancellation included) this weekend :)

Oh, just for reference, this is the 0.8-dev branch (still not ready for everyday use):
https://github.com/Dax89/harbour-sailorgram/tree/0.8

And this, is the new library used by 0.8 (developed by me, from scratch): https://github.com/Dax89/LibTelegram

**Comment by JustDevZero** [comment]
@Dax89 I imagined that's in mind for 0.8, can't wait to see it...

And for the reference, yup, I tried to compile it by my self and didn't work yet :package: 

So, as far as I can see, 0.8 will be a LOT different and better. Keep the good work comming.

Have you got in mind sending 0.8 (when it's finished) to QA for including it into the Jolla Store?

**Comment by Dax89** [comment]
A lot of work is needed in order to bring back 0.7x series features (without bugs, of course :P).

The new library is in good shape, in fact the only thing to do is to create the corrispondent Telegram type and write a nice class around it in order to become usable in qml.

Yes, I will send the 0.8 in the Jolla Store (without the service) and, I will also make available a service based client in OpenRepos :)

**Comment by Dax89** [comment]
Fixed in upstream
