### ISSUE TITLE
Sticker issues

### ISSUE THREAD

**Issue by huuhaa** [Dax89/harbour-sailorgram#83]
First things first. I open this as a new issue, cause older ones are ether closed or not quite fit for this. This all could and probably is only user error, but anyway...

Problem: When I choose send sticker at Sailorgram, there is text "Choose sticker set from below" or similar (I'm using Finnish translation so texts are not exactly like I translate here), but there is no sticker set to choose! I also tried following: When my friend sent me few stickers, I longpressed those and choose Install sticker set, one by one. Still there is no sticker set available to send for. When I go to Settings to check error logs (after trying to install received sticker), there is errormessge:

Errorcode: 400
Task (?): messagesGetStickerSet
Message: STICKERSET_INVALID

(not sure should it read task there, but I think you know what I mean anyway...)

So what am I doing wrong, should I install sticker set manually somehow? I have uninstalled and installed Sailorgram again + tried to remove folder /home/nemo/.local/share/harbour-sailorgram but no luck. I am assuming that sticker should work nowdays out of the box, am I right?

**Comment by Dax89** [comment]
It's the default sticker set?

**Comment by huuhaa** [comment]
If you mean that sticker I received, I have no idea is it default, but would quess it is. I wonder does my friend know either, he just testing telegram windows phone app and didn't even know where to find sticker (or what sticker is) at first. First time I saw one too.. :D (just trying to move toward telegram)

But what comes to Sailorgram, should I have default sticker set installed by default? Right now I have none.

**Comment by Dax89** [comment]
Usually that error comes out when you are trying to instal the default sticker set.

Yes it the default one should be shipped with Sailorgram
I need to study the library's source code in order to do it, currently it displays only custom sets, that's why you don't see any.

**Comment by huuhaa** [comment]
Ok, I see. Thanks! Btw what is currently right way to install custom sets?

**Comment by Dax89** [comment]
When someone sends a custom sticker, long press it and click the "Install" option :)

**Comment by mentaljam** [comment]
I also have a question about stickers. It doesn't concern to the original issue but I think it's better to ask it here.

When you open the main selectors page at the first time after the application restart it freezes for some seconds (the reason seems to be in [stickers initialization](https://github.com/Dax89/harbour-sailorgram/blob/master/harbour-sailorgram/qml/pages/selector/SelectorMainPage.qml#L22-L27)). Sometimes OS even shows a "Wait for response" message. May be it's better to initialize stickers on the application start?

**Comment by Dax89** [comment]
Yes sticker initialization is pretty slow and it causes the selector page to freeze until stickers are loaded.
It would be great to put in in a secondary thread (maybe patching directly TelegramQML's model?)

I have tried to put it at startup but we are moving the "freeze" during that phase and it's not pretty.

**Comment by Dax89** [comment]
Fixed in upstream
