### ISSUE TITLE
Image thumbnails when adding attachment

### ISSUE THREAD

**Issue by asgeirrr** [Dax89/harbour-sailorgram#9]
Thank you for this great client (and developing it out in the open), it's moving forward at an impressive pace. One enhancement that came to my mind is showing image thumbnail when adding an attachment. One view for selecting all the different kind of attachments is fine at the moment I guess but the thumbnail feature would enable us to find the right picture.

**Comment by Dax89** [comment]
Hi!

Thumbnails was enabled in 0.7.
I have disabled it because they triggers the Out Of Memory Killer (especially in folders with lots of pictures), currently I'm looking for a good solution :)

**Comment by oskholl** [comment]
I see, I had no idea. Thank you for the update and good luck finding the solution.

**Comment by Dax89** [comment]
:+1: 
See issue #3 for more info! :)

**Comment by PawelSpoon** [comment]
@asgeirrr 
you can flattr also on stuff that is in Github
you need to connect github with flattr and then any repository in github that you star will get something
it is described in the jolla announcement
cheers
