### ISSUE TITLE
Add support for super groups

### ISSUE THREAD

**Issue by PureTryOut** [Dax89/harbour-sailorgram#90]
Telegram introduced supergroups, which I believe are just regular groups but support for something like 5000 people.

One of the group chats I'm in converted to such a group, and I now can't receive any messages from that group anymore.

**Comment by Dax89** [comment]
It's a known "issue" (discovered months ago).
I'm waiting for new LibQTelegram and TelegramQML in order to implement that.

**Comment by PureTryOut** [comment]
Ooh, I didn't see an issue for it. My bad then.

**Comment by Dax89** [comment]
No problem! :+1:

**Comment by Dax89** [comment]
Fixed in upstream
